name: weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.8
  either_dart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  http: ^1.4.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/weather-storm.jpg
    - assets/images/weather-day-partlycloudy.jpg
    - assets/images/weather-day-cloudy.jpg
    - assets/images/weather-day-sunny.jpg
    - assets/images/weather-rainy.jpg
    - assets/images/weather-fog.jpg